pipeline {
    agent any
  tools {
    gradle 'Gradle 6.5'
  }

    stages {
        // TODO. shared pipeline 공통화 예정
        stage('Checkout Application Git Branch') {
            steps {
                git branch: '${RELEASE_BRANCH}',
                    credentialsId: 'github_credential',
                    url: 'https://github.com/yoganara/yoganara_api.git'
            }
        }
        stage('Gradle Project build') {
            steps {
                sh '''
                ./gradlew clean bootJar
                '''
            }
        }
    }
}