#!groovy
pipeline {
    agent any
    options {
        timeout(time: 10, unit: "MINUTES")
        timestamps()
    }
    tools {
        jdk('java8')
        gradle 'Gradle 6.5'
    }

    stages {
        stage('Clean Workspace') {

        }
        stage('Checkout Application Git Branch') {
            steps {
                git branch: '${RELEASE_BRANCH}',
                        credentialsId: 'github_credential',
                        url: 'https://github.com/yoganara/yoganara_api.git'
            }
        }
        stage('Gradle Project build') {
            steps {
                sh '''
                ./gradlew clean bootJar
                '''
            }
        }
    }
}